import axios from "axios";
import { apisApp } from "./apis";
import { ValuesFilter } from "./interfaces";

export const ServicesApp = () => {
  const fetchPaginatedData = (
    page = 0,
    pageSize = 10,
    body = {},
    exactFilters = [],
    rangeFilters = []
  ) => {
    return axios.post(`${apisApp.baseBackend}/filter`, {
      page,
      pageSize,
      body,
      exactFilters,
      rangeFilters,
    });
  };

  return {
    fetchPaginatedData,
  };
};

// comunidades_tags:
export const arrayComunidades_tags: ValuesFilter[] = [
  { text: "", value: "" },
  { text: "Asturias", value: "asturias" },
  { text: "Galicia", value: "galicia" },
  { text: "Murcia", value: "murcia" },
  { text: "Balears", value: "balears" },
  { text: "Madrid", value: "madrid" },
  { text: "Extremadura", value: "extremadura" },
  { text: "Melilla", value: "melilla" },
  { text: "Andalucía", value: "andalucia" },
  { text: "Castilla y León", value: "castilla_y_leon" },
  { text: "Cataluña", value: "cataluna" },
  { text: "Comunitat Valenciana", value: "comunitat_valenciana" },
  { text: "Aragón", value: "aragon" },
  { text: "Canarias", value: "canarias" },
  { text: "Cantabria", value: "cantabria" },
  { text: "Ceuta", value: "ceuta" },
  { text: "La Rioja", value: "la_rioja" },
  { text: "Navarra", value: "navarra" },
  { text: "País Vasco", value: "pais_vasco" },
  { text: "Baleares", value: "baleares" },
  { text: "Castilla-La Mancha", value: "castilla_la_mancha" },
  { text: "Euskadi", value: "euskadi" },
];

// provincia_tags:
export const arrayProvincia_tags: ValuesFilter[] = [
  { text: "", value: "" },
  { text: "Alta Verapaz", value: "alta_verapaz" },
  { text: "Baja Verapaz", value: "baja_verapaz" },
  { text: "Chimaltenango", value: "chimaltenango" },
  { text: "Chiquimula", value: "chiquimula" },
  { text: "Guatemala", value: "guatemala" },
  { text: "El Progreso", value: "el_progreso" },
  { text: "Escuintla", value: "escuintla" },
  { text: "Huehuetenango", value: "huehuetenango" },
  { text: "Izabal", value: "izabal" },
  { text: "Jalapa", value: "jalapa" },
  { text: "Jutiapa", value: "jutiapa" },
  { text: "Petén", value: "peten" },
  { text: "Quetzaltenango", value: "quetzaltenango" },
  { text: "Quiché", value: "quiche" },
  { text: "Retalhuleu", value: "retalhuleu" },
  { text: "Sacatepéquez", value: "sacatepequez" },
  { text: "San Marcos", value: "san_marcos" },
  { text: "Santa Rosa", value: "santa_rosa" },
  { text: "Sololá", value: "solola" },
  { text: "Suchitepéquez", value: "suchitepequez" },
  { text: "Totonicapán", value: "totonicapan" },
  { text: "Zacapa", value: "zacapa" },
  { text: "Mixco", value: "mixco" },
  { text: "Villa Nueva", value: "villa_nueva" },
  { text: "Chinautla", value: "chinautla" },
  { text: "Amatitlán", value: "amatitlan" },
  { text: "Villa Canales", value: "villa_canales" },
  { text: "San José Pinula", value: "san_jose_pinula" },
  { text: "Santa Catarina Pinula", value: "santa_catarina_pinula" },
  { text: "Fraijanes", value: "fraijanes" },
  { text: "Palencia", value: "palencia" },
  { text: "San Juan Sacatepéquez", value: "san_juan_sacatepequez" },
  { text: "San Pedro Ayampuc", value: "san_pedro_ayampuc" },
  { text: "San Raymundo", value: "san_raymundo" },
  { text: "Chuarrancho", value: "chuarrancho" },
  { text: "Patzicía", value: "patzicia" },
  { text: "Patzún", value: "patzun" },
  { text: "Santa Apolonia", value: "santa_apolonia" },
  { text: "Tecpán Guatemala", value: "tecpan_guatemala" },
  { text: "San Andrés Itzapa", value: "san_andres_itzapa" },
  { text: "Comalapa", value: "comalapa" },
  { text: "San José Poaquil", value: "san_jose_poaquil" },
  { text: "San Juan Comalapa", value: "san_juan_comalapa" },
  { text: "Santa Cruz Balanyá", value: "santa_cruz_balanya" },
  { text: "San Martín Jilotepeque", value: "san_martin_jilotepeque" },
  { text: "San Miguel Chicaj", value: "san_miguel_chicaj" },
  { text: "Rabinal", value: "rabinal" },
  { text: "Cubulco", value: "cubulco" },
  { text: "Granados", value: "granados" },
  { text: "Purulhá", value: "purulha" },
  { text: "Tactic", value: "tactic" },
  { text: "Tamahú", value: "tamahu" },
  { text: "Tucurú", value: "tucuru" },
  { text: "Panzós", value: "panzos" },
  { text: "Cahabón", value: "cahabon" },
  { text: "Lanquín", value: "lanquin" },
  { text: "Chisec", value: "chisec" },
  { text: "Santa Cruz Verapaz", value: "santa_cruz_verapaz" },
  { text: "Santa María Cahabón", value: "santa_maria_cahabon" },
  { text: "Chahal", value: "chahal" },
  { text: "Raxruhá", value: "raxruha" },
  { text: "San Pedro Carchá", value: "san_pedro_carcha" },
  { text: "Santa Catalina La Tinta", value: "santa_catalina_la_tinta" },
  { text: "San Juan Chamelco", value: "san_juan_chamelco" },
  { text: "San Cristóbal Verapaz", value: "san_cristobal_verapaz" },
  { text: "Cobán", value: "coban" },
  { text: "Chiquimulilla", value: "chiquimulilla" },
  { text: "Barberena", value: "barberena" },
  { text: "Oratorio", value: "oratorio" },
  { text: "Cuilapa", value: "cuilapa" },
  { text: "Taxisco", value: "taxisco" },
  { text: "Nueva Santa Rosa", value: "nueva_santa_rosa" },
  { text: "Casillas", value: "casillas" },
  { text: "Santa María Ixhuatán", value: "santa_maria_ixhuatan" },
  { text: "San Rafael Las Flores", value: "san_rafael_las_flores" },
  { text: "Pueblo Nuevo Viñas", value: "pueblo_nuevo_vinas" },
  { text: "San Juan Tecuaco", value: "san_juan_tecuaco" },
  { text: "Guazacapán", value: "guazacapan" },
  { text: "Santa Cruz Naranjo", value: "santa_cruz_naranjo" },
  { text: "San Cristóbal Cucho", value: "san_cristobal_cucho" },
  { text: "San Pablo", value: "san_pablo" },
  { text: "San Pedro Sacatepéquez", value: "san_pedro_sacatepequez" },
  { text: "San Rafael Pie de la Cuesta", value: "san_rafael_pie_de_la_cuesta" },
  { text: "San Marcos", value: "san_marcos" },
  { text: "Concepción Tutuapa", value: "concepcion_tutuapa" },
  { text: "Comitancillo", value: "comitancillo" },
  { text: "El Quetzal", value: "el_quetzal" },
  { text: "El Tumbador", value: "el_tumbador" },
  { text: "Ixchiguán", value: "ixchiguan" },
  { text: "La Blanca", value: "la_blanca" },
  { text: "La Reforma", value: "la_reforma" },
  { text: "Malacatán", value: "malacatan" },
  { text: "Nuevo Progreso", value: "nuevo_progreso" },
  { text: "Ocos", value: "ocos" },
  { text: "Pajapita", value: "pajapita" },
  { text: "Río Blanco", value: "rio_blanco" },
  { text: "San Antonio Sacatepéquez", value: "san_antonio_sacatepequez" },
  { text: "San Cristóbal Acasaguastlán", value: "san_cristobal_acasaguastlan" },
  { text: "San Jerónimo", value: "san_jeronimo" },
  { text: "San José La Arada", value: "san_jose_la_arada" },
  { text: "San Sebastián", value: "san_sebastian" },
  { text: "Santa Catarina Mita", value: "santa_catarina_mita" },
  { text: "Santa Lucía Cotzumalguapa", value: "santa_lucia_cotzumalguapa" },
  { text: "Santa María Visitación", value: "santa_maria_visitacion" },
  { text: "Santiago Atitlán", value: "santiago_atitlan" },
  { text: "Santo Domingo Xenacoj", value: "santo_domingo_xenacoj" },
  { text: "Sibilia", value: "sibilia" },
  { text: "Sipacapa", value: "sipacapa" },
  { text: "Tacaná", value: "tacana" },
  { text: "Zunilito", value: "zunilito" },
];

// municipios_tags:
export const arrayMunicipios_tags: ValuesFilter[] = [
  { text: "", value: "" },
  { text: "Gijón", value: "gijon" },
  { text: "Oviedo", value: "oviedo" },
  { text: "Tarragona", value: "tarragona" },
  { text: "Amposta", value: "amposta" },
  { text: "Ares", value: "ares" },
  { text: "Plan", value: "plan" },
  { text: "Orbita", value: "orbita" },
  { text: "Santiago de Compostela", value: "santiago_de_compostela" },
  { text: "Murcia", value: "murcia" },
  { text: "Palma", value: "palma" },
  { text: "Real", value: "real" },
  { text: "Eivissa", value: "eivissa" },
  { text: "Formentera", value: "formentera" },
  { text: "Ourense", value: "ourense" },
  { text: "Madrid", value: "madrid" },
  { text: "Béjar", value: "bejar" },
  { text: "Salamanca", value: "salamanca" },
  { text: "Ciudad Rodrigo", value: "ciudad_rodrigo" },
  { text: "Chamartín", value: "chamartin" },
  { text: "Fuentes", value: "fuentes" },
  { text: "Fuentes de Oñoro", value: "fuentes_de_onoro" },
  { text: "Sagra", value: "sagra" },
  { text: "Carbajo", value: "carbajo" },
  { text: "Ronda", value: "ronda" },
  { text: "Reina", value: "reina" },
  { text: "Talavera", value: "talavera" },
  { text: "Talavera de la Reina", value: "talavera_de_la_reina" },
  { text: "Toledo", value: "toledo" },
  { text: "Ávila", value: "avila" },
  { text: "Cuenca", value: "cuenca" },
  { text: "Valladolid", value: "valladolid" },
  { text: "Gavilanes", value: "gavilanes" },
  { text: "Pedro Bernardo", value: "pedro_bernardo" },
  { text: "Prado", value: "prado" },
  { text: "Grado", value: "grado" },
  { text: "Adanero", value: "adanero" },
  { text: "León", value: "leon" },
  { text: "Segovia", value: "segovia" },
  { text: "Segura", value: "segura" },
  { text: "Vic", value: "vic" },
  { text: "Pol", value: "pol" },
  { text: "Parla", value: "parla" },
  { text: "Fiscal", value: "fiscal" },
  { text: "Torrella", value: "torrella" },
  { text: "Benidorm", value: "benidorm" },
  { text: "Benissa", value: "benissa" },
  { text: "Finestrat", value: "finestrat" },
  { text: "Torrevieja", value: "torrevieja" },
  { text: "Calp", value: "calp" },
  { text: "Orihuela", value: "orihuela" },
  { text: "Ciudad Real", value: "ciudad_real" },
  { text: "Alcázar de San Juan", value: "alcazar_de_san_juan" },
  { text: "Mérida", value: "merida" },
  { text: "Almadén", value: "almaden" },
  { text: "Puertollano", value: "puertollano" },
  { text: "Bolaños de Calatrava", value: "bolanos_de_calatrava" },
  { text: "Fuente el Fresno", value: "fuente_el_fresno" },
  { text: "Langreo", value: "langreo" },
  { text: "Avilés", value: "aviles" },
  { text: "Badajoz", value: "badajoz" },
  { text: "Almendral", value: "almendral" },
  { text: "Almendralejo", value: "almendralejo" },
  { text: "Don Benito", value: "don_benito" },
  { text: "Jerez de los Caballeros", value: "jerez_de_los_caballeros" },
  { text: "Villanueva de la Serena", value: "villanueva_de_la_serena" },
  { text: "Zafra", value: "zafra" },
  { text: "Almendra", value: "almendra" },
  { text: "Alburquerque", value: "alburquerque" },
  { text: "Guadiana", value: "guadiana" },
  { text: "Herrera del Duque", value: "herrera_del_duque" },
  { text: "Cáceres", value: "caceres" },
  { text: "Talavera", value: "talavera" },
  { text: "Llerena", value: "llerena" },
  { text: "Fregenal de la Sierra", value: "fregenal_de_la_sierra" },
  { text: "Castelló", value: "castello" },
  { text: "Granada", value: "granada" },
  { text: "Sevilla", value: "sevilla" },
  { text: "Mairena del Alcor", value: "mairena_del_alcor" },
  { text: "Arahal", value: "arahal" },
  { text: "Antequera", value: "antequera" },
  { text: "Venta de Baños", value: "venta_de_banos" },
  { text: "Simancas", value: "simancas" },
  { text: "Tordesillas", value: "tordesillas" },
  { text: "Campo", value: "campo" },
  { text: "Palencia", value: "palencia" },
  { text: "Medina del Campo", value: "medina_del_campo" },
  { text: "Siétamo", value: "sietamo" },
  { text: "Lleida", value: "lleida" },
  { text: "Almudévar", value: "almudevar" },
  { text: "Zaragoza", value: "zaragoza" },
  { text: "Huesca", value: "huesca" },
  { text: "Canfranc", value: "canfranc" },
  { text: "Nava", value: "nava" },
  { text: "Lorca", value: "lorca" },
  { text: "Cartagena", value: "cartagena" },
  { text: "Barcelona", value: "barcelona" },
  { text: "Lugo", value: "lugo" },
  { text: "Monforte de Lemos", value: "monforte_de_lemos" },
  { text: "Vilamartín de Valdeorras", value: "vilamartin_de_valdeorras" },
  { text: "Portas", value: "portas" },
  { text: "Amoeiro", value: "amoeiro" },
  { text: "Pedralba", value: "pedralba" },
  { text: "Girona", value: "girona" },
  { text: "Selva", value: "selva" },
  { text: "Pont de Molins", value: "pont_de_molins" },
  { text: "Figueres", value: "figueres" },
  { text: "Bàscara", value: "bascara" },
  { text: "Garrigàs", value: "garrigas" },
  { text: "Vidreres", value: "vidreres" },
  { text: "Besalú", value: "besalu" },
  { text: "Cabanelles", value: "cabanelles" },
  { text: "Ribes de Freser", value: "ribes_de_freser" },
  { text: "Vigo", value: "vigo" },
  { text: "Teruel", value: "teruel" },
  { text: "Bilbao", value: "bilbao" },
  { text: "Hondarribia", value: "hondarribia" },
  { text: "San Sebastián", value: "san_sebastian" },
  { text: "Vitoria", value: "vitoria" },
  { text: "Zarautz", value: "zarautz" },
  { text: "Gernika", value: "gernika" },
];
